const Events = [
  {
    key: '1',
    title: 'iMovie 101',
    date: 'Lun, 25 Gen',
    start_time: '09:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Milano',
    address: 'Piazza Castello 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
  {
    key: '2',
    title: 'xCode',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'tech',
    free: true,
  },
  {
    key: '3',
    title: 'After Effect',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
  {
    key: '4',
    title: 'CleanMyMac',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
  {
    key: '5',
    title: 'Photoshop',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
  {
    key: '6',
    title: 'Final Cut Pro',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
  {
    key: '7',
    title: 'Numbers',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
  {
    key: '8',
    title: 'Pages',
    date: 'Gio, 28 Gen',
    start_time: '15:00',
    end_time: '16:00',
    img: require('./assets/imovie.jpg'),
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    city: 'Torino',
    address: 'Via Savoia 3',
    planner: 'Apple',
    max_attendance: '50',
    category: 'edu',
    free: true,
  },
]

export default Events

// to do
// eventi numero chiuso
// categoria eventi
