const Events = [
  {
    key: '1',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '2',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '3',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '4',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '5',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '6',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '7',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '8',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
]

export default Events
