const Events = [
  {
    key: '1',
    title: 'iMovie 101',
    start_date: '25-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '2',
    title: 'Xcode',
    start_date: '28-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Torino',
    planner: 'Apple',
  },
  {
    key: '3',
    title: 'After Effect',
    start_date: '23-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Bologna',
    planner: 'Adobe',
  },
  {
    key: '4',
    title: 'CleanMyMac',
    start_date: '22-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Roma',
    planner: 'MacPaw',
  },
  {
    key: '5',
    title: 'Photoshop',
    start_date: '28-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Bologna',
    planner: 'Adobe',
  },
  {
    key: '6',
    title: 'Final Cut Pro',
    start_date: '30-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '7',
    title: 'Numbers',
    start_date: '22-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
  {
    key: '8',
    title: 'Pages',
    start_date: '30-01-2021',
    end_date: '27-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
    location: 'Milano',
    planner: 'Apple',
  },
]

export default Events
