const News = [
  {
    key: '1',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit lorem ipsum dolor sit amet...',
  },
  {
    key: '2',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '3',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '4',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '5',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '6',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '7',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '8',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '9',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '10',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '11',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '12',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
  {
    key: '13',
    title: 'Lorem ipsum dolor sit...',
    date: '25-01-2021',
    img: './assets/imovie.jpg',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit...',
  },
]

export default News
